# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Curso Zetha
email: lucastaliberti@gmail.com
description: Página para o Curso Zetha de Programação
baseurl: "/curso-zetha-programacao" # the subpath of your site, e.g. /blog
url: "http://lucastaliberti.github.io/curso-zetha-programacao/" # the base hostname & protocol for your site
twitter_username: lucastaliberti
github_username:  lucastaliberti

# Build settings
markdown: kramdown

# pages
include: ['_pages']
